### ISSUE TITLE
Mouse support for TTYs?

### ISSUE THREAD

**Issue by xplshn** [RealMelkor/Vgmi#3]
I use this in NetBSD and Alpine Linux, my setup doesn't have neither X nor Wayland, not even Bash, I'd love to see support for GPM and what nBSD uses for mouse support... Thanks for this! Its awesome! Also, another question; Commands for everything + tab completion would be very handy! So that I don't have to refer to the help page so much!

**Comment by RealMelkor** [comment]
Thanks. I added some mouse support in the last commit.
It allows clicking links and switching tabs, but right now it most likely only works in terminal emulators.
I'm not too sure yet how to make GPM works with termbox(the TUI library that Vgmi uses) since I think GPM has ncurses as a dependency.
I will probably start looking at "moused" on NetBSD/FreeBSD first.

For the "commands for everything", could you recommend some commands that you think are missing?
Since I feel there's already a command for most hotkeys/actions in Vgmi.

And for the tab completion, yes it's something that I could implement eventually.

**Comment by xplshn** [comment]
There is the option to use Consolation: https://salsa.debian.org/consolation-team/consolation
But it is worse, its based on libinput...

By commands for everything I meant:
:open
:new-tab
:next_tab
:previous_tab
etc, I meant to also add commands for the basic actions.

THanks!

**Comment by RealMelkor** [comment]
Greetings,

I added support for GPM, it seems to work fine on my end.
To compile Vgmi with GPM support you will need to uncomment the two lines in the GNUmakefile file.

For the commands, there already was the command tabnew, I added an alias ":open" to the ":o" command.
I also added the commands "tabnext" and "tabprev". I try to keep the same command names as in Vim.
I will implement tab-completion eventually.

**Comment by xplshn** [comment]
Great! I will compile and notify you about the results! Thank you!

**Comment by xplshn** [comment]
It works! Tho it needs some polishing, other programs select the button with one click, and only really press the buttons when you do a double click, that's what elinks and many other programs based on ncurses do.

**Comment by RealMelkor** [comment]
I tested elinks and it seems to open links when the mouse button is released instead of on double clicks.
I added something similar, Vgmi now selects the link when pressing it and only open the link if the click is released while the cursor is still on it.

I also added tab completion, similar to what is in Vim.

**Comment by xplshn** [comment]
🎉 Thanks!
